### ISSUE TITLE
Custom javascript included on global level when unessecary

### ISSUE THREAD

**Issue by PeteyRev** [oBundle/tules-cookies#4]
Some of the custom js files you created are being unnecessarily included on a global level, we need to make use of webpacks code splitting feature.

Example: `ob-fancybox.js` is only being used for the lightbox for the product pages, but is being included in `global.js`. This should only be included in `product-details.js`

`ob-instafeed.js` It seems that this is being removed from the project, so it needs to be removed from the code

`ob-categorycartadd.js` should only be included in `category.js`

**Comment by PeteyRev** [comment]
@jay-psdcenter where are we on this one?

**Comment by jay-psdcenter** [comment]
We have done with the above changes as per your given instruction.

**Comment by PeteyRev** [comment]
@jay-psdcenter Thanks!
